project:
  type: website
  resources:
    - CNAME
    - media/
  output-dir: docs
lang: en

website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** I am available for a postdoctoral position starting in July 2025. Please do not hesitate to contact me for opportunities or collaborations 😉"
    type: danger
    position: below-navbar
  title: "Corentin Maslard"
  favicon: media/growing-plant.png
  back-to-top-navigation: true
  site-url: "https://cmaslard.xyz"
  repo-url: "https://github.com/cmaslard/cmaslard.github.io"
  google-analytics: "G-10GPM4RSNJ"
  navbar:
    left:
      - href: index.qmd
        text: " "
      - href: me.qmd
      - text: Projects
        href: work_projects.qmd
      - href: publications.qmd
      - href: presentations.qmd
      - text: Others
        menu: 
          - text: Supervised Students
            href: advisees.qmd
          - text: Awards
            href: awards.qmd
          - text: Grants
            href: grants.qmd
          - text: Tools
            href: tools.qmd
          - text: Personal projects
            href: perso_projects.qmd

  page-footer: 
      border: true
      left: 
        - icon: badge-cc-fill
          url: https://creativecommons.org/licenses/by-nc-sa/4.0/
        - text: "Corentin Maslard 2024"
          href: "https://cmaslard.xyz/" 
        
      center:
        - text: "{{< iconify fa6-solid:envelope >}}"
          href: "mailto:maslard.corentin@gmail.com"
          aria-label: "envelope logo for email"
        - text: "{{< iconify fa6-brands:github >}}"
          href: https://github.com/cmaslard
        - text: "{{< iconify fa6-brands:linkedin >}}"
          href: https://www.linkedin.com/in/corentin-maslard
        - text: "{{< iconify fa6-brands square-x-twitter >}}"
          href: https://x.com/cmaslard
        - text: "{{< iconify fa6-brands bluesky >}}"
          href: https://bsky.app/profile/cmaslard.bsky.social
        - text: "{{< iconify fa6-brands:orcid >}}"
          href: "https://orcid.org/0000-0002-6951-1963"
          aria-label: "ORCID logo linking to ORCID account"
        - text: "{{< iconify fa6-brands:researchgate >}}"
          href: "https://www.researchgate.net/profile/Corentin-Maslard"
          aria-label: "ResearchGate logo linking to ResearchGate account"
        - text: "{{< iconify academicons:google-scholar >}}"
          href: https://scholar.google.com/citations?user=TsztyiMAAAAJ&hl
          target: blank
        - text: "{{< iconify academicons:hal >}}"
          href: https://cv.hal.science/corentinmaslard
          aria-label: "HAL account"
        - text: "{{< iconify pepicons-pop:cv >}}"
          href: "https://docs.google.com/document/d/1oCgrdjnAJuVjgocx3F2kmlbJxlqa6uWrSgqm5fWRhpA/edit?usp=sharing"
          aria-label: "CV"
      right:
          <span class="faux-block">Made with <iconify-icon icon="line-md:heart-twotone"></iconify-icon>, <iconify-icon icon="line-md:coffee-twotone-loop"></iconify-icon>, {{< iconify fa6-brands r-project >}} and [Quarto](https://quarto.org/)</span> |
          <span class="faux-block">[View the source at {{< iconify fa6-brands github >}} GitHub](https://github.com/cmaslard/cmaslard.github.io)</span>

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
    toc: false
