---
title: Welcome !
subtitle: The philosophy behind this site
title-block-banner: media/tree-banner.jpg
title-block-banner-color: "#FFFFFF"
about:
  template: solana
---

Hi, I am Corentin and this is my research website!

My research aims to understand how **plants** can better adapt to changes in **water availability** and rising temperatures throughout their growth cycle. To do this, my PhD research explored how water and heat stress influence root system architecture and shape interactions with soil **microbial communities**, aiming to uncover traits and mechanisms that improve plant resilience. Given the complexity of plant–microorganism relationships, this work required innovative and **integrative** strategies. I applied plant phenotyping techniques alongside advanced data analysis tools, including **deep learning** and **multi-omics** approaches such as high-throughput sequencing, metabolomics, and ionomics. By merging computational methods with cutting-edge biological knowledge, I aim to push the boundaries of plant research and contribute to the creation of resilient agricultural systems.

I believe in **Open Science** and the importance of science communication.

I am currently working as a postdoctoral researcher in Switzerland at the [University of Neuchâte](https://www.unine.ch/), in the Laboratory of [Plant Molecular and Cell Biology led by Prof. Joop Vermeer](https://www.unine.ch/lbmc). My research focuses on **root system architecture** and its adaptive mechanisms under stress, particularly **lateral root formation** in *Brachypodium distachyon*, combining molecular approaches, multiphoton microscopy, snRNA-seq, and genetic variability analyses
