---
title: "Publications"
format: 
  html:
    grid: 
      sidebar-width: 0px
      body-width: 1200px
      margin-width: 0px
      gutter-width: 1rem
editor: visual
---


|N° | Title       | Author      | Journal | File          |
|---|----------------|----------------|----------------|-------------------|
|4|Decoding the Double Stress Puzzle: Investigating Nutrient Uptake Efficiency and Root Architecture in Soybean under Heat- and Water- Stresses | **Corentin Maslard**, Mustapha Arkoun, Fanny Leroy, Sylvie Girodet, Christophe Salon and  Marion Prudent | Plant, Cell & Environment | <span class="faux-block"><iconify-icon icon="mdi:unlocked-variant-outline" width="1.2em" height="1.2em"  style="color: #58a53b"></iconify-icon> <iconify-icon icon="line-md:cog-loop" width="1.2em" height="1.2em"  style="color: #58a53b"></iconify-icon></span>|
|3| Ectopic expression of the grape hexose transporter VvHT5 restores STP13-deficiency in *Arabidopsis* and promotes fungal resistance to *Botrytis cinerea* | Benoit Monnereau, Cécile Gaillard, **Corentin Maslard**, Pierre-Antoine Noceto, Anne Cantereau, Pierre Coutos-Thévenot and Sylvain La Camera | - | <span class="faux-block"></iconify-icon> <iconify-icon icon="line-md:cog-loop" width="1.2em" height="1.2em"  style="color: #58a53b"></iconify-icon></span> |
|2| Root architecture characterization in relation to biomass allocation and biological nitrogen fixation in a collection of European soybean genotypes| **Corentin Maslard**, Mustapha Arkoun, Christophe Salon and Marion Prudent | OCL | <span class="faux-block">[{{< iconify line-md:download-loop width="1.2em" height="1.2em" >}}](media/publications/2.pdf) [{{< iconify line-md link width="1.2em" height="1.2em" >}}](https://doi.org/10.1051/ocl/2021033) <iconify-icon icon="mdi:unlocked-variant-outline" width="1.2em" height="1.2em"  style="color: #58a53b"></span> |
|1| Pentadecaibins I−V: 15-Residue Peptaibols Produced by a Marine-Derived *Trichoderma* sp. of the *Harzianum* Clade         | Anne-Isaline van Bohemen, Nicolas Ruiz, Aurore Zalouk-Vergnoux, Aurore Michaud, Thibaut Robiou du Pont, Irina Druzhinina, Lea Atanasova, Soizic Prado, Bernard Bodo, Laurence Meslet-Cladiere, Bastien Cochereau, Franck Bastide, **Corentin Maslard**, Muriel Marchi, Thomas Guillemette and Yves François Pouchus | Journal of Natural Products| <span class="faux-block">[{{< iconify line-md:download-loop width="1.2em" height="1.2em" >}}]( media/publications/1.pdf) [{{< iconify line-md link width="1.2em" height="1.2em" >}}](https://dx.doi.org/10.1021/acs.jnatprod.0c01355)</span>|