name: Render and Deploy Quarto

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'  # Tous les jours à 6h (UTC)

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "release"

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'  # Adapte selon ta version de R
          
      - name: Install R dependencies
        run: |
          install.packages("remotes")
          if (file.exists("DESCRIPTION")) {
            remotes::install_deps(dependencies = TRUE)
          } else if (file.exists("renv.lock")) {
            install.packages("renv")
            renv::restore()
          } else {
            install.packages(c("tidyverse", 
                               "ggplot2",
                               "rcrossref",
                               "readxl",
                               "patchwork",
                               "treemap",
                               "leaflet",
                               "htmlwidgets", 
                               "htmltools",
                               "googleway",
                               "plotly",
                               "scholar",
                               "knitr",
                               "kableExtra", 
                               "glue",
                               "stringr",
                               "readr",
                               devoid))
          }
          # Vérification que devtools est bien installé
          remotes::install_github('ropensci/rAltmetric')
          remotes::install_github('nsgrantham/ggdark')
        shell: Rscript {0}

      - name: Render Quarto site
        run: |
          quarto render

      - name: Pull latest changes to avoid conflicts
        run: |
          git pull --rebase

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Automated Quarto render and push" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
