name: Render and Deploy Quarto

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * *'  # Tous les jours à 6h (UTC)

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "release"

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2'

      # Installer les dépendances système utiles pour certains packages
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      # Option : si vous n'avez pas de fichier DESCRIPTION, utilisez une clé statique pour le cache
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.R/library
          key: ${{ runner.os }}-r-packages
          restore-keys: |
            ${{ runner.os }}-r-packages

      - name: Install R dependencies
        env:
          GITHUB_PAT: ${{ secrets.FOR_IMPORT_GITHUBPACKAGE_PAT }}  # Assurez-vous que ce secret est défini
        run: |
          install.packages("remotes", repos="https://cloud.r-project.org")
          install.packages(c("tidyverse", 
                             "ggplot2",
                             "rcrossref",  
                             "readxl",
                             "patchwork",
                             "treemap",
                             "leaflet",
                             "htmlwidgets", 
                             "htmltools",
                             "googleway",
                             "plotly",
                             "knitr",
                             "kableExtra", 
                             "glue",
                             "stringr",
                             "readr"), repos="https://cloud.r-project.org")
          # Installation de scholar depuis GitHub uniquement
          remotes::install_github('YuLab-SMU/scholar')
        shell: Rscript {0}
        
      - name: List installed packages
        run: Rscript -e "print(installed.packages()[, c('Package','Version')])"
          
      - name: Check installed packages
        run: Rscript -e "if(!('rcrossref' %in% rownames(installed.packages()))) { stop('rcrossref is not installed') } else { print('rcrossref is installed') }"

      - name: Test scholar package
        run: Rscript -e "library(scholar); cat('scholar is installed successfully\n')"
      
      - name: Render Quarto site
        run: quarto render

      - name: Pull latest changes to avoid conflicts
        run: git pull --rebase

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Automated Quarto render and push" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
